name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: flutter format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --coverage

      - name: Build APK
        run: flutter build apk --debug

      - name: Build Web
        run: flutter build web
